### PR TITLE
initial peek styles

### PR DESCRIPTION
**Pull request by kjell**

### CODE REVIEW

**Comment by kjell** [comment]
(superseeds #13)

Looks good. A few things:

- [ ]  On hover, the red 'view more results' it turns black and gets lost in the background image

- [ ] Does 'View more results' work better on a newline? Or right aligned?
image 
image

- [ ] Should the black box extend to the full width of the page when it's mostly empty?
image

**Comment by kjell** [comment]
How do we deal with Peeks that have results with no image?

image

I like showing the title, but it breaks down at small scale. Shrinking the font is a start, and because it's more "atmospheric" (to give someone an idea of what's there) I think it's OK to fudge readability a bit

image

**Comment by niffur** [comment]
funny, I was just going to make these changes when I got back from lunch. line height is way too big now though, we'll have to adjust that.

did you push this up?

**Comment by niffur** [comment]
These changes I mean. I like this.

**Comment by niffur** [comment]
what page is that on with the grey background? can we make the peek-click area offset with grey like that if it's open? I really like that and I was playing with a border on top of the peek and I couldn't get it to look good

**Comment by kjell** [comment]
[The gray is on all object pages](http://collection.staging.artsmia.org/art/59937/milling-district-gold-medal-flour-vernon-howe-bailey).

**Comment by niffur** [comment]
It's not on my branch which was pulled for master last week.

thoughts?

screen shot 2015-09-28 at 2 34 41 pm

**Comment by kjell** [comment]
I like it, but I also want to keep 'noise' in the tombstone/label text to a minimum. For showing the connection between the term and the activated peek I think it works without being too distracting.

**Comment by kjell** [comment]
And hmm. I still have gray on my object pages. If white is better we should change it #17

**Comment by emhavens** [comment]
The related content branch is using a white background on object pages. I like it because it is consistent with the previews and the rest of the site.

**Comment by niffur** [comment]
the problem without the individual peek delineations on ones without images, they tend to run together.

**Comment by niffur** [comment]
i guess If we make sure there is always abt 15px of padding in the RH side of the box it could work without the lines

**Comment by kjell** [comment]
I don't mind the lines if we can only put them where there isn't an image. Right-padding sounds a little bit better to me if you can get it to work.

I have code for the right-aligned "view more results", should I push it or would that step on your toes?

**Comment by niffur** [comment]
Push away! :)

**Comment by kjell** [comment]
(rebased and merged to master)

**Pull request closed without merging**
