### PR TITLE
initial no image styles

### PR DESCRIPTION
**Pull request by niffur**

### CODE REVIEW

**Comment by kjell** [comment]
Should these have a min-height to give them a bit more space?

image

Should we connect the bar at the bottom of the results with the patches above it? (to "close" the box)

image
image

This also affects the quilt on the homepage and peeks, intended? I think it's great on the Peeks, maybe not the homepage quilt:

image

**Comment by niffur** [comment]
huh I didn't see that weird bar thing before. Yes the styling affects the home page quilt too. I've haven't gotten that far of taking it out of the home page quilt. The shorter boxes don't really bother me, they seem to have plenty of space

**Comment by kjell** [comment]
When there are lots of results with no image they lose their "semi-consistent grid", I'll explain with screenshots

Before, each text box got a "bucketed" width/height according to how many words are in the title. There were only 2 buckets: normal and wider. So consecutive rows without images sort of lined up:

[image](http://collection.staging.artsmia.org/search/artist:%22Francis%20Seymour%20Haden%22)

Now with the `flex-grow: 1` each box gets a different amount of space which looks a bit more haphazard:

image

It turns the text-only results into a tangle of words and makes them hard to scan.

**Comment by niffur** [comment]
Hmm I guess I don't really have an issue with it. Maybe get rid of the bold text. The top one ins't easier to scan IMHO, the spacing seems odd

**Comment by niffur** [comment]
I do think the bold is too harsh though

**Comment by niffur** [comment]
screen shot 2015-10-30 at 2 23 22 pm

**Comment by niffur** [comment]
screen shot 2015-10-30 at 3 48 07 pm

**Comment by niffur** [comment]
Also `flex-grow:1` was on it before too. 

old code
`var style = {
      display: 'inline-block',
      verticalAlign: 'top',
      overflow: 'hidden',
      width: width,
      height: width/art.aspect_ratio
    }
var textStyle = {
      ...style,
      backgroundColor: '#fff',
      padding: '0.25em',
      flexGrow: 1,
      whiteSpace: 'normal',
    }
`

**Comment by kjell** [comment]
It might just be that the borders really emphasize the random grid

**Comment by niffur** [comment]
I think you're right, I'll look at how to de-emphasize that.

**Comment by kjell** [comment]
I don't not like it, but it does stand out

**Comment by niffur** [comment]
screen shot 2015-10-30 at 3 57 14 pm
screen shot 2015-10-30 at 3 57 38 pm

**Comment by niffur** [comment]
screen shot 2015-11-02 at 9 57 08 am

returned the faux grid, lightened the borders

**Comment by niffur** [comment]
vertically centered

screen shot 2015-11-02 at 10 30 37 am

**Pull request closed without merging**
