### PR TITLE
Toolbar

### PR DESCRIPTION
**Pull request by kjell**

### CODE REVIEW

**Comment by kjell** [comment]
image

**Comment by niffur** [comment]
? Not sure what is happening here

**Comment by kjell** [comment]
It's breaks at small screen sizes

**Comment by niffur** [comment]
shouldn't the right and left sides be fixed to the viewport sides and a flexible div ( `display:table-cell` ) in the middle?

**Comment by emhavens** [comment]
I will take a look. I understand what is happening I am unsure what the solution is, but will dig into it now.

**Comment by kjell** [comment]
@emhavens @niffur how does this look for the active list/grid icon?

image

**Comment by niffur** [comment]
OOO! I love it!

**Comment by kjell** [comment]
Maybe round the "filter search" box as well?

image &rarr; image

**Comment by niffur** [comment]
hmm, no, it think that's too much deviation from the brand styles. I def like it for the buttons though, it has a nice contrast to the sharp corners of the icon

**Pull request merged**
