### PR TITLE
New styles for artwork preview in search results

### PR DESCRIPTION
**Pull request by niffur**
Consolidated and cleaned up header for 'objects-focus'
Moved Gallery into the header
centered images in the pane
Fixed line-heights in header to match brand guides
Added a grey background for some orientation
Removed unnecessary black bar
Added link color to the clickable stuff

### CODE REVIEW

**Comment by niffur** [comment]
Need to move the gallery# to the left, pls dont merge yet

**Comment by niffur** [comment]
OK fixed that

**Comment by emhavens** [comment]
Here is a link to a possible alternative view of the results : https://github.com/artsmia/art/tree/minimal-results-view

Primary goal : Remove all distraction from the images and condense white space where possible.

List view
	-removed boxshadow and gray background to the area.
	- used text alignment to create visual grid.
	- removed action items from list view -- Action on left pane is to preview
	-moved text to right of image to utilize white space and condense the list view

Preview pane
	-add action icons to bottom of preview description.
	-moved all text below the image to keep the text cohesive and to feature the image above the text
	-positioned image left to create a visual divider between the list view and the preview using the edge of the image

**Comment by niffur** [comment]
The list view is looking good on your new branch

**Comment by kjell** [comment]
I manually merged these changed with @emhavens's, trying to get the best of both.

[Let's all have a look](http://collection.staging.artsmia.org/) and see if I missed anything important

**Pull request merged**
